sudo: true
dist: trusty
language: node_js
node_js: 8.9

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

env:
  - POLYMER=polymer2
  - POLYMER=polymer3

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      if [[ "$POLYMER" = "polymer2" ]]; then
        npm install;
        bower install;
        wct --env saucelabs;
      fi;
      if [[ "$POLYMER" = "polymer3" ]]; then
        npm install -g bower json yarn web-component-tester;
        (cd .. && git clone git://github.com/polymer/polymer-modulizer.git && cd polymer-modulizer && npm link);
        json -I -f package.json -e 'this.devDependencies = {}';
        bower i;
        modulizer --out . --force;
        yarn install --flat;
        wct --npm --env saucelabs-p3;
      fi;
    fi
